"use strict";
// FluidNC alarm and error descriptions (from FluidNC 4.1.1 Alarm.h / Error.h).
const ALARMS = {
  1: "Hard limit triggered - position lost, re-home",
  2: "Soft limit - target outside machine travel",
  3: "Reset while moving - position may be lost, re-home",
  4: "Probe fail - probe already triggered before start",
  5: "Probe fail - probe did not make contact",
  6: "Homing fail - reset during homing",
  7: "Homing fail - door opened during homing",
  8: "Homing fail - pull-off did not clear the switch",
  9: "Homing fail - limit switch not found",
  10: "Spindle control error",
  11: "Control or limit input active at startup",
  12: "Homing fail - ambiguous switch",
  13: "Hard stop",
  14: "Machine not homed",
  15: "Initialisation / config problem",
  16: "Expander reset",
  17: "G-code error during job",
  18: "Probe hit a hard limit",
};
const ERRORS = {
  1: "G-code word missing a letter", 2: "Bad number format", 3: "Invalid $ statement",
  4: "Negative value", 5: "Setting disabled", 6: "Step pulse too short", 7: "Settings read failed",
  8: "Machine must be idle", 9: "Locked out (alarm or jog active)", 10: "Soft limits need homing",
  11: "Overflow", 12: "Step rate too high", 13: "Safety door open", 14: "Line too long",
  15: "Jog target exceeds travel", 16: "Invalid jog command", 17: "Laser mode needs PWM",
  18: "No homing cycles configured", 19: "Single-axis homing not allowed",
  20: "Unsupported G-code", 21: "Modal group violation", 22: "Feed rate not set",
  23: "Value must be an integer", 24: "Two commands use the same axis", 25: "Repeated word",
  26: "No axis words", 27: "Invalid line number", 28: "Missing value", 29: "Unsupported work offset",
  30: "G53 needs G0 or G1", 31: "Axis words with no motion", 32: "Arc has no plane axes",
  33: "Invalid target", 34: "Arc radius error", 35: "Arc missing offset", 36: "Unused words",
  37: "Tool length offset axis error", 38: "Value too large", 39: "P parameter too large",
  40: "Startup pin active",
  60: "Filesystem mount failed", 61: "File read failed", 62: "Directory open failed",
  63: "Directory not found", 64: "File is empty", 65: "File not found", 66: "File open failed",
  67: "Filesystem busy", 68: "Directory delete failed", 69: "File delete failed", 70: "Rename failed",
  80: "Number out of range", 81: "Invalid value", 82: "File create failed", 83: "Format failed",
  90: "Message failed", 100: "Settings save failed", 110: "Authentication failed",
  120: "Another interface is busy (job running)", 130: "Jog cancelled",
  150: "Bad pin specification", 151: "Bad runtime config setting", 152: "Configuration invalid",
  160: "Upload failed", 161: "Download failed", 162: "Read-only setting",
  170: "Expression: divide by zero", 171: "Expression: invalid argument", 172: "Expression: invalid result",
  173: "Expression: unknown op", 174: "Expression: argument out of range", 175: "Expression syntax error",
  176: "Flow control syntax error", 177: "Flow control outside a macro", 178: "Flow control out of memory",
  179: "Flow control stack overflow", 180: "Parameter assignment failed", 181: "Invalid G-code value",
};
